// <auto-generated />
namespace KnowledgeBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbcontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbcontext));
        
        string IMigrationMetadata.Id
        {
            get { return "201702141529572_dbcontext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
